name: flutter_flow
description: 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.3.0
  cupertino_icons: ^1.0.2
  dio: 5.4.0
  dio_cache_interceptor: 3.5.0
  dio_cache_interceptor_hive_store: 3.2.2
  flutter_riverpod: 2.4.9
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.1
  go_router: 12.1.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  json_serializable: 6.7.1
  persistent_bottom_nav_bar: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: 2.4.7
  freezed: 2.4.5
  hive_generator: 2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
